language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: JmqnPUwKc0xTo9ghWtM+Ap5gGPEBrp5HwG64916EVjb5x4tCGtpJftSh0p/wf7WeRAu8ZAGce3oXKo8Rf+YTvuPzKQiLvi1hECE5EsULBZWv0Bfmo/j3H8xBqNTWXWnhgSx/UgbLCSyEwRmzcvnN+R+Qjgz0LxPrkmVpuenzwcLYVa5BzIOE9LergYGSkKDhhQAMabDA81Js5kYpCQxlda40kNIeIWauvdRi9G7MlOHrQqzosaFkqrFzx6tepk1QhuBDCV4jE9wZv9+eb9BL5uPF6/K6rkv87i/WSLJxTNmthw9tqQk5Pf+ebMcTroRhjf51YoIk53KEPNZf7TRZUSlAPvSfHkgrjS7Muy240ISmItDELPL+8QzwJSJ5oyvsKpmV/gU3o3mhvOEIGxRkq0IrA4Ico02SAuUqhRS1FAKM40ogjc51I6BeZYd+952RjZno+b/JOeRTYFT94yOQ+s3EVpCWt8CI2+7ohNe/Ggowy02pJLhf3MJjTZLLUoRrFaRO8IZJaFflHxsFZDBq+0U11wd0kLhM6vHNqLXWnIGQE8hXFhRVccmnZ1Mgxy477vhGP1OksD/afofZqGsSUZeGQSShkTvmxXyi2n3rzEtxK3PUQcDaynBy9K3oTg89WlEd1Ett5guCNUqImdM5q94PsgeOyZvOUnxtizTLugM=
